// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBG3phQTaOfARz9zn2RI1eFn4-mH3C_b-k',
    appId: '1:16542249499:web:6440a14794ac3722e3bebe',
    messagingSenderId: '16542249499',
    projectId: 'fir-app2-2e462',
    authDomain: 'fir-app2-2e462.firebaseapp.com',
    storageBucket: 'fir-app2-2e462.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBak-hVuhpG3c8VApeDjXowvrK6hLIJT3A',
    appId: '1:16542249499:android:5fc346d870c85239e3bebe',
    messagingSenderId: '16542249499',
    projectId: 'fir-app2-2e462',
    storageBucket: 'fir-app2-2e462.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCncegQ8I1HE2F5L9lyFXyFabFbfsvR8b4',
    appId: '1:16542249499:ios:c7b9d2816e89dc0ee3bebe',
    messagingSenderId: '16542249499',
    projectId: 'fir-app2-2e462',
    storageBucket: 'fir-app2-2e462.appspot.com',
    iosBundleId: 'com.example.firebaseApp2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCncegQ8I1HE2F5L9lyFXyFabFbfsvR8b4',
    appId: '1:16542249499:ios:c7b9d2816e89dc0ee3bebe',
    messagingSenderId: '16542249499',
    projectId: 'fir-app2-2e462',
    storageBucket: 'fir-app2-2e462.appspot.com',
    iosBundleId: 'com.example.firebaseApp2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBG3phQTaOfARz9zn2RI1eFn4-mH3C_b-k',
    appId: '1:16542249499:web:f513dccdcd4b74b2e3bebe',
    messagingSenderId: '16542249499',
    projectId: 'fir-app2-2e462',
    authDomain: 'fir-app2-2e462.firebaseapp.com',
    storageBucket: 'fir-app2-2e462.appspot.com',
  );
}
